apiVersion: v1
kind: Service
metadata:
  name: {{ include "producer-consumer-name" . }}-backend-service
spec:
  type: ClusterIP
  selector:
    app: {{ include "producer-consumer-name" . }}-server
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.targetPort }}
