apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.ui.path }}
            backend:
              serviceName: {{ .Release.Name }}-{{ .Chart.Name }}-ui-service
              servicePort: {{ .Values.ingress.ui.servicePort }}
          - path: {{ .Values.ingress.backend.path }}
            backend:
              serviceName: {{ .Release.Name }}-{{.Chart.Name}}-backend-service
              servicePort: {{ .Values.ingress.backend.servicePort }}