apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "producer-consumer-name" . }}-server
spec:
  selector:
    matchLabels:
      app: {{ include "producer-consumer-name" . }}-server
  template:
    metadata:
      labels:
        app: {{ include "producer-consumer-name" . }}-server
    spec:
      containers:
      - name: {{ include "producer-consumer-name" . }}-server
        image: {{ .Values.backend.deployment.image }}
        livenessProbe:
          httpGet:
            path: {{ .Values.backend.liveness.path }}
            port: {{ .Values.backend.liveness.port }}
          initialDelaySeconds: {{ .Values.backend.liveness.initialDelay }}
          periodSeconds: {{ .Values.backend.liveness.periodSeconds }}
        ports:
        - containerPort: {{ .Values.backend.deployment.port }}
