apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{.Chart.Name}}-backend-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-server
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.targetPort }}
