apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "producer-consumer-name" . }}-web
spec:
  selector:
    matchLabels:
      app: {{ include "producer-consumer-name" . }}-web
  template:
    metadata:
      labels:
        app: {{ include "producer-consumer-name" . }}-web
    spec:
      containers:
      - name: {{ include "producer-consumer-name" . }}-web
        image: {{ .Values.ui.deployment.image }}
        ports:
        - containerPort: {{ .Values.ui.deployment.port }}