apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-web
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}-web
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}-web
    spec:
      containers:
      - name: {{ .Release.Name }}-{{ .Chart.Name }}-web
        image: {{ .Values.ui.deployment.image }}
        ports:
        - containerPort: {{ .Values.ui.deployment.port }}