apiVersion: v1
kind: Service
metadata:
  name: {{ include "producer-consumer-name" . }}-ui-service
spec:
  type: ClusterIP
  selector:
    app: {{ include "producer-consumer-name" . }}-web
  ports:
  - port: {{ .Values.ui.service.port }}
    targetPort: {{ .Values.ui.service.targetPort }}
